### PR TITLE
Hi i Changed the login button name from Login to Let's! Connect

### PR DESCRIPTION
**Pull request by Muralidhargithub**
Hi every one can you please review and update me

### CODE REVIEW

**Comment by shobhakartiwari** [comment]
next time try to put pr title short and try not to include I , We , you. Approved

**Comment by Anusha0070** [comment]
Hello Muralidhar!

The code looks good!

**Comment by ikdoo1004** [comment]
It's good to go.

**Comment by DharmaMithraTirunagari** [comment]
Your code looks good!

**Comment by shobhakartiwari** [comment]
Follow this next time : 
This PR includes : - 
JIRA Ticket: 101 [ url ] 
Description : 
Test User : 
Screenshot / Recording :

**Comment by yash13199** [comment]
Approved.

**Pull request merged**
